name: Déploiement vers Vercel

# Condition de déclenchement
on:
  push:
    branches:
      - main # Déclenchement sur la branche principale (main)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: # Aligné avec runs-on
      # 1. Checkout du code source
      - name: Checkout du code
        uses: actions/checkout@v3

      # 2. Installation de Node.js et des dépendances
      - name: Installation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Installation des dépendances
        run: npm install

      # 3. Construire l'application React
      - name: Build de l'application
        run: npm run build

      # 4. Déployer sur Vercel
      - name: Déploiement
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          vercel --prod --token $VERCEL_TOKEN --yes

  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Nécessaire pour une analyse correcte

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonarqube-scanner